# Generated by Django 4.2.2 on 2023-07-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_date', models.TextField(blank=True, null=True)),
                ('tr_year', models.IntegerField(blank=True, null=True)),
                ('tr_mon', models.IntegerField(blank=True, null=True)),
                ('st_no', models.TextField(blank=True, null=True)),
                ('st_name', models.TextField(blank=True, null=True)),
                ('number_04_05_getin', models.IntegerField(blank=True, db_column='04-05_GetIn', null=True)),
                ('number_04_05_getout', models.IntegerField(blank=True, db_column='04-05_GetOut', null=True)),
                ('number_05_06_getin', models.IntegerField(blank=True, db_column='05-06_GetIn', null=True)),
                ('number_05_06_getout', models.IntegerField(blank=True, db_column='05-06_GetOut', null=True)),
                ('number_06_07_getin', models.IntegerField(blank=True, db_column='06-07_GetIn', null=True)),
                ('number_06_07_getout', models.IntegerField(blank=True, db_column='06-07_GetOut', null=True)),
                ('number_07_08_getin', models.IntegerField(blank=True, db_column='07-08_GetIn', null=True)),
                ('number_07_08_getout', models.IntegerField(blank=True, db_column='07-08_GetOut', null=True)),
                ('number_08_09_getin', models.IntegerField(blank=True, db_column='08-09_GetIn', null=True)),
                ('number_08_09_getout', models.IntegerField(blank=True, db_column='08-09_GetOut', null=True)),
                ('number_09_10_getin', models.IntegerField(blank=True, db_column='09-10_GetIn', null=True)),
                ('number_09_10_getout', models.IntegerField(blank=True, db_column='09-10_GetOut', null=True)),
                ('number_10_11_getin', models.IntegerField(blank=True, db_column='10-11_GetIn', null=True)),
                ('number_10_11_getout', models.IntegerField(blank=True, db_column='10-11_GetOut', null=True)),
                ('number_11_12_getin', models.IntegerField(blank=True, db_column='11-12_GetIn', null=True)),
                ('number_11_12_getout', models.IntegerField(blank=True, db_column='11-12_GetOut', null=True)),
                ('number_12_13_getin', models.IntegerField(blank=True, db_column='12-13_GetIn', null=True)),
                ('number_12_13_getout', models.IntegerField(blank=True, db_column='12-13_GetOut', null=True)),
                ('number_13_14_getin', models.IntegerField(blank=True, db_column='13-14_GetIn', null=True)),
                ('number_13_14_getout', models.IntegerField(blank=True, db_column='13-14_GetOut', null=True)),
                ('number_14_15_getin', models.IntegerField(blank=True, db_column='14-15_GetIn', null=True)),
                ('number_14_15_getout', models.IntegerField(blank=True, db_column='14-15_GetOut', null=True)),
                ('number_15_16_getin', models.IntegerField(blank=True, db_column='15-16_GetIn', null=True)),
                ('number_15_16_getout', models.IntegerField(blank=True, db_column='15-16_GetOut', null=True)),
                ('number_16_17_getin', models.IntegerField(blank=True, db_column='16-17_GetIn', null=True)),
                ('number_16_17_getout', models.IntegerField(blank=True, db_column='16-17_GetOut', null=True)),
                ('number_17_18_getin', models.IntegerField(blank=True, db_column='17-18_GetIn', null=True)),
                ('number_17_18_getout', models.IntegerField(blank=True, db_column='17-18_GetOut', null=True)),
                ('number_18_19_getin', models.IntegerField(blank=True, db_column='18-19_GetIn', null=True)),
                ('number_18_19_getout', models.IntegerField(blank=True, db_column='18-19_GetOut', null=True)),
                ('number_19_20_getin', models.IntegerField(blank=True, db_column='19-20_GetIn', null=True)),
                ('number_19_20_getout', models.IntegerField(blank=True, db_column='19-20_GetOut', null=True)),
                ('number_20_21_getin', models.IntegerField(blank=True, db_column='20-21_GetIn', null=True)),
                ('number_20_21_getout', models.IntegerField(blank=True, db_column='20-21_GetOut', null=True)),
                ('number_21_22_getin', models.IntegerField(blank=True, db_column='21-22_GetIn', null=True)),
                ('number_21_22_getout', models.IntegerField(blank=True, db_column='21-22_GetOut', null=True)),
                ('number_22_23_getin', models.IntegerField(blank=True, db_column='22-23_GetIn', null=True)),
                ('number_22_23_getout', models.IntegerField(blank=True, db_column='22-23_GetOut', null=True)),
                ('number_23_24_getin', models.IntegerField(blank=True, db_column='23-24_GetIn', null=True)),
                ('number_23_24_getout', models.IntegerField(blank=True, db_column='23-24_GetOut', null=True)),
                ('number_00_01_getin', models.IntegerField(blank=True, db_column='00-01_GetIn', null=True)),
                ('number_00_01_getout', models.IntegerField(blank=True, db_column='00-01_GetOut', null=True)),
                ('number_01_02_getin', models.IntegerField(blank=True, db_column='01-02_GetIn', null=True)),
                ('number_01_02_getout', models.IntegerField(blank=True, db_column='01-02_GetOut', null=True)),
                ('number_02_03_getin', models.IntegerField(blank=True, db_column='02-03_GetIn', null=True)),
                ('number_02_03_getout', models.IntegerField(blank=True, db_column='02-03_GetOut', null=True)),
                ('number_03_04_getin', models.IntegerField(blank=True, db_column='03-04_GetIn', null=True)),
                ('number_03_04_getout', models.IntegerField(blank=True, db_column='03-04_GetOut', null=True)),
                ('getin_total', models.IntegerField(blank=True, null=True)),
                ('getout_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_tr',
                'managed': False,
            },
        ),
    ]
